# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#u1 = User.create(first_name: 'Augusto', last_name: "Samame", username: "986976377", email: "augustosamame@gmail.com", password: "marianna", role: "admin", status: 0)
#u2 = User.create(first_name: 'Arnaldo', last_name: "Azabache", username: "993306393", email: "oxxono@gmail.com", password: "123456", role: "admin", status: 0)
#u3 = User.create(first_name: 'Hemant', last_name: "Nangia", username: "989080023", email: "gg@expatshop.pe", password: "123456", role: "admin", status: 0)
Ecommerce::Control.create(name: 'remove_no_stock_products', localized_name: 'Remove No Stock Products', value_field_type: "boolean", boolean_value: true)
Ecommerce::Control.create(name: 'invoice_terms_and_conditions', localized_name: 'Terms and Conditions for Invoices', value_field_type: "text", text_value: "No se aceptan cambios o devoluciones")
Ecommerce::Control.create(name: 'show_top_bar', localized_name: 'Show Top Bar', value_field_type: "boolean", boolean_value: true )
Ecommerce::Control.create(name: 'top_bar_cookie_read_hash', localized_name: 'Top Bar Cookie Read Hash', internal: true, value_field_type: "text")
Ecommerce::Control.create(name: 'top_bar_html', localized_name: 'Top Bar HTML', value_field_type: "text", text_value: "Back to the future of awesome Bags: Introducing the best bags in the world. <a href='#'>Shop Now</a>")
Ecommerce::Control.create(name: 'store_title', localized_name: 'Store Title', value_field_type: "text", text_value: "Put Store Title Here")
Ecommerce::Control.create(name: 'auto_invoice', localized_name: 'Auto Invoice', value_field_type: "boolean", boolean_value: false )
Ecommerce::Control.create(name: 'auto_ship', localized_name: 'Auto Ship', value_field_type: "boolean", boolean_value: false )
Ecommerce::Control.create(name: 'efact_url', localized_name: 'Efact Url', value_field_type: "text", text_value: "http://localhost:3001/invoice" )
Ecommerce::Control.create(name: 'efact_token', localized_name: 'Efact Token', value_field_type: "text", text_value: "12345678901234566111" )
Ecommerce::Control.create(name: 'next_boleta_number', localized_name: 'Next Boleta Number', value_field_type: "integer", integer_value: 1 )
Ecommerce::Control.create(name: 'next_boleta_number', localized_name: 'Next Factura Number', value_field_type: "integer", integer_value: 1 )
Ecommerce::Control.create(name: 'next_nota_de_credito_boleta_number', localized_name: 'Next Nota de Crédito Boleta Number', value_field_type: "integer", integer_value: 1 )
Ecommerce::Control.create(name: 'next_nota_de_credito_factura_number', localized_name: 'Next Nota de Crédito Factura Number', value_field_type: "integer", integer_value: 1 )
Ecommerce::Control.create(name: 'default_taxes', localized_name: 'Default Tax list (tax1,amount1,tax2,amount2)', value_field_type: "text", text_value: "IGV,18" )
Ecommerce::Control.create(name: 'exchange_rate', localized_name: 'Exchange Rate', value_field_type: "float", float_value: 3.60)

Ecommerce::Control.create(name: 'flat_shipping_cutoff_amount', localized_name: 'Flat Shipping Cutoff Amount in USD', value_field_type: "float", float_value: 30 )
Ecommerce::Control.create(name: 'flat_shipping_under_cutoff_rate', localized_name: 'Flat Shipping Under Cutoff Rate', value_field_type: "float", float_value: 4 )
Ecommerce::Control.create(name: 'flat_shipping_over_cutoff_rate', localized_name: 'Flat Shipping Over Cutoff Rate', value_field_type: "float", float_value: 1.50 )

Ecommerce::Control.create(name: "drip_email_1_active", localized_name: "Drip Email 1 Active", value_field_type: "boolean", boolean_value: false, internal: false)

Ecommerce::Control.create(name: "drip_email_1_event_type", localized_name: "Drip Email 1 Event Type", value_field_type: "text", text_value: "user_signup", internal: false)

Ecommerce::Control.create(name: "drip_email_1_days_after_event", localized_name: "Drip Email 1 Days After Event", value_field_type: "integer", integer_value: 3, internal: false)

Ecommerce::Control.create(name: "drip_email_1", localized_name: "Drip Email 1 Email Name", value_field_type: "text", text_value: "drip_email_1_signup", internal: false)

Ecommerce::Control.create(name: "drip_email_2_active", localized_name: "Drip Email 2 Active", value_field_type: "boolean", boolean_value: false, internal: false)

Ecommerce::Control.create(name: "drip_email_2_event_type", localized_name: "Drip Email 2 Event Type", value_field_type: "text", text_value: "user_signup", internal: false)

Ecommerce::Control.create(name: "drip_email_2_days_after_event", localized_name: "Drip Email 2 Days After Event", value_field_type: "integer", integer_value: 15, internal: false)

Ecommerce::Control.create(name: "drip_email_2", localized_name: "Drip Email 2 Email Name", value_field_type: "text", text_value: "drip_email_2_signup", internal: false)

Ecommerce::Control.create(name: "drip_email_3_active", localized_name: "Drip Email 3 Active", value_field_type: "boolean", boolean_value: false, internal: false)

Ecommerce::Control.create(name: "drip_email_3_event_type", localized_name: "Drip Email 3 Event Type", value_field_type: "text", text_value: "user_signup", internal: false)

Ecommerce::Control.create(name: "drip_email_3_days_after_event", localized_name: "Drip Email 3 Days After Event", value_field_type: "integer", integer_value: 60, internal: false)

Ecommerce::Control.create(name: "drip_email_3", localized_name: "Drip Email 3 Email Name", value_field_type: "text", text_value: "drip_email_3_signup", internal: false)

Ecommerce::Control.create(name: "send_abandoned_cart_email_active", localized_name: "Abandoned Cart Emails Active", value_field_type: "boolean", boolean_value: false, internal: false)

Ecommerce::Tax.create(tax_name: "IGV", tax_friendly_name: "Impuesto General a las Ventas")
Ecommerce::Tax.create(tax_name: "ISC", tax_friendly_name: "Impuesto Selectivo al Consumo")

Ecommerce::Slider.create(slider_name: 'Home Slider 1', slider_text: "", remote_slider_image_url: "https://s3.amazonaws.com/v1-devtechperu-expatshop-dev/static/images/home/Sliders/marinmeko+slider.jpg", slider_view: "Desktop", slider_order: 1 )
Ecommerce::Slider.create(slider_name: 'Home Slider 2', slider_text: "", remote_slider_image_url: "https://s3.amazonaws.com/v1-devtechperu-expatshop-dev/static/images/home/Sliders/babyganics.jpg", slider_view: "Mobile", slider_order: 2 )

pm1 = Ecommerce::PaymentMethod.create(name: "Card", processor: "Culqi", status: "active")
pm2 = Ecommerce::PaymentMethod.create(name: "Bank Deposit", status: "active")
pm3 = Ecommerce::PaymentMethod.create(name: "Manual", status: "active")
pm4 = Ecommerce::PaymentMethod.create(name: "PagoEfectivo", status: "active")

Ecommerce::Brand.create!([
  {name: "Dr. Brown", logo: "organici_logo.png"},
  {name: "Babyganics", logo: "organici_logo.png"},
  {name: "Mr Clean", logo: "organici_logo.png"},
  {name: "Czech Crystal", logo: "organici_logo.png"},
  {name: "Amar Te", logo: "Logo.jpg"},
  {name: "IHR", logo: nil}
])
Ecommerce::Supplier.create!([
  {name: "Importer Name", logo: nil, tax_id: nil, tax_id_type: nil, default_hours_lead_time: nil},
  {name: "Andrea Kovacs", logo: "Amar Te", tax_id: "20603295855", tax_id_type: nil, default_hours_lead_time: nil},
  {name: "IHR", logo: "IHR", tax_id: "", tax_id_type: nil, default_hours_lead_time: nil}
])
Ecommerce::Category.create!([
  {name: "Disposable Table Runners", parent_id: 16, status: "active", category_type: "primary", category_order: 7, main_menu: true, popular: false, popular_homepage: false, image_popular_homepage: nil, image_popular_homepage_overlay_text: "Disposable Table Runners", homepage_cat_image_width: nil, homepage_cat_image_height: nil},
  {name: "Cocktail Napkins", parent_id: 16, status: "active", category_type: "primary", category_order: 0, main_menu: true, popular: false, popular_homepage: false, image_popular_homepage: nil, image_popular_homepage_overlay_text: "Cocktail Napkins", homepage_cat_image_width: nil, homepage_cat_image_height: nil},
  {name: "Large Napkins", parent_id: 16, status: "active", category_type: "primary", category_order: 1, main_menu: true, popular: false, popular_homepage: false, image_popular_homepage: nil, image_popular_homepage_overlay_text: "Large Napkins", homepage_cat_image_width: nil, homepage_cat_image_height: nil},
  {name: "Organic Tea", parent_id: nil, status: "active", category_type: "primary", category_order: 10, main_menu: true, popular: false, popular_homepage: false, image_popular_homepage: nil, image_popular_homepage_overlay_text: "Organic Tea", homepage_cat_image_width: nil, homepage_cat_image_height: nil},
  {name: "Embossed Napkins", parent_id: 16, status: "active", category_type: "primary", category_order: 3, main_menu: true, popular: false, popular_homepage: false, image_popular_homepage: nil, image_popular_homepage_overlay_text: "Embossed Napkins", homepage_cat_image_width: nil, homepage_cat_image_height: nil},
  {name: "Dinner Napkin", parent_id: 16, status: "active", category_type: "primary", category_order: 4, main_menu: true, popular: false, popular_homepage: false, image_popular_homepage: nil, image_popular_homepage_overlay_text: "Dinner Napkins", homepage_cat_image_width: nil, homepage_cat_image_height: nil},
  {name: "Dripless Taper Candles", parent_id: 16, status: "active", category_type: "primary", category_order: 8, main_menu: true, popular: false, popular_homepage: false, image_popular_homepage: nil, image_popular_homepage_overlay_text: "Dripless Taper Candles", homepage_cat_image_width: nil, homepage_cat_image_height: nil},
  {name: "House of Germany", parent_id: nil, status: "active", category_type: "secondary", category_order: 0, main_menu: true, popular: false, popular_homepage: true, image_popular_homepage: nil, image_popular_homepage_overlay_text: "House of Germany", homepage_cat_image_width: nil, homepage_cat_image_height: nil},
  {name: "House of Arab", parent_id: nil, status: "inactive", category_type: "secondary", category_order: 16, main_menu: true, popular: false, popular_homepage: true, image_popular_homepage: nil, image_popular_homepage_overlay_text: "House of Arab", homepage_cat_image_width: "400.0", homepage_cat_image_height: "233.0"},
  {name: "Textile Touch Napkins", parent_id: 16, status: "active", category_type: "primary", category_order: 5, main_menu: true, popular: false, popular_homepage: false, image_popular_homepage: nil, image_popular_homepage_overlay_text: "Textile Touch Napkins", homepage_cat_image_width: nil, homepage_cat_image_height: nil}
])
Ecommerce::Product.create!([
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Hearts", short_description: "", description: "Hearts", permalink: "Hearts", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Bunnies in Love", short_description: "", description: "Bunnies in Love", permalink: "Bunnies in Love", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Let's Celebrate", short_description: "", description: "Let's Celebrate", permalink: "Let's Celebrate", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Organic Tea"], brand_id: 5, supplier_id: 2, name: "Box of 9 Blends", short_description: "", description: "Organic Tea Box of 9 Blends - Cacao, Green tea, Black tea, Mango, Apple, Red Fruits, Herbal, Floral, Andean Mint", permalink: "Box of 9 Blends", price_cents: 17000, discounted_price_cents: 17000, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Vintage Angel", short_description: "", description: "Vintage Angel", permalink: "Vintage Angel", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Hip Hip Hooray", short_description: "", description: "Hip Hip Hooray", permalink: "Hip Hip Hooray", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Happy Beersday", short_description: "", description: "Happy Beersday", permalink: "Happy Beersday", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Palais Red", short_description: "", description: "Palais Red", permalink: "Palais Red", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Baloons", short_description: "", description: "Baloons", permalink: "Baloons", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Blue Lilies", short_description: "", description: "Blue Lilies", permalink: "Blue Lilies", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of USA", "Household"], brand_id: 1, supplier_id: 1, name: "Bra Ball", short_description: "Bra Washer Protector Ball prevents winding among clothes.", description: "Design:a big hollow bra ball+a small clothes massage ball,just put underwear and small massage ball into big bra ball,then put it into washing machine,flower hollow design,fashion and launder bras without damage, protect bras from tangling and snagging. Safe alternative to hand washing,saving time,and washing cleaner.Keeps hooks from bending,cups keep their shape,bras last longer and look better. Suitable for all type of bras and bathing suits,also can be used as a suitcase travel bra protector.", permalink: "Bra Ball", price_cents: 3000, discounted_price_cents: 3000, meta_keywords: nil, meta_description: nil, stockable: false, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: "El Bra Ball the permite introducir el bra en una bola de plástico que podrá lavase en la lavadora sin dañar el bra, ni el resto de la ropa en la lavadora. Una segura alternativa a lavar a mano, ahorrando tiempo y obteniendo un mejor lavado."},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Wedding Rings", short_description: "", description: "Wedding Rings", permalink: "Wedding Rings", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Horses", short_description: "", description: "Horses", permalink: "Horses", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Baby Girl", short_description: "", description: "Baby Girl", permalink: "Baby Girl", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Cocktail Napkins"], brand_id: 6, supplier_id: 3, name: "Baby Boy", short_description: "", description: "Baby Boy", permalink: "Baby Boy", price_cents: 890, discounted_price_cents: 890, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Large Napkins"], brand_id: 6, supplier_id: 3, name: "Paris", short_description: "", description: "Paris", permalink: "Paris", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Large Napkins"], brand_id: 6, supplier_id: 3, name: "Germany", short_description: "", description: "Germany", permalink: "Germany", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Large Napkins"], brand_id: 6, supplier_id: 3, name: "London", short_description: "", description: "London", permalink: "London", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Large Napkins"], brand_id: 6, supplier_id: 3, name: "Football", short_description: "", description: "Football", permalink: "Football", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Large Napkins", "House of Germany"], brand_id: 6, supplier_id: 3, name: "We Are The Champions", short_description: "", description: "We Are The Champions", permalink: "We Are The Champions", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Embossed Napkins"], brand_id: 6, supplier_id: 3, name: "Gold Royalty", short_description: "", description: "Gold Royalty", permalink: "Gold Royalty", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Embossed Napkins"], brand_id: 6, supplier_id: 3, name: "Festive Time", short_description: "", description: "Festive Time", permalink: "Festive Time", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Embossed Napkins"], brand_id: 6, supplier_id: 3, name: "Red Hearts", short_description: "", description: "Red Hearts", permalink: "Red Hearts", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Embossed Napkins"], brand_id: 6, supplier_id: 3, name: "Silver Royalty", short_description: "", description: "Pack of 16 Napkins", permalink: "Silver Royalty", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["House of Germany", "Embossed Napkins"], brand_id: 6, supplier_id: 3, name: "Embossed Gold Hearts", short_description: "", description: "Pack of 16 Napkins", permalink: "Embossed Gold Hearts", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Embossed Napkins"], brand_id: 6, supplier_id: 3, name: "Saffron Royalty", short_description: "", description: "Pack of 16 Napkins", permalink: "Saffron Royalty", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Embossed Napkins"], brand_id: 6, supplier_id: 3, name: "Gold Hearts", short_description: "", description: "Pack of 16 Napkins", permalink: "Gold Hearts", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Embossed Napkins"], brand_id: 6, supplier_id: 3, name: "Green Royalty", short_description: "", description: "Pack of 16 Napkins", permalink: "Green Royalty", price_cents: 1390, discounted_price_cents: 1390, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Dinner Napkin"], brand_id: 6, supplier_id: 3, name: "Palais Red Dinner Napkins", short_description: "", description: "Pack of 16 Napkins", permalink: "Palais Red Dinner Napkins", price_cents: 1590, discounted_price_cents: 1590, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Dinner Napkin"], brand_id: 6, supplier_id: 3, name: "Grandeur Gold", short_description: "", description: "Pack of 16 Napkins", permalink: "Grandeur Gold", price_cents: 1590, discounted_price_cents: 1590, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Dinner Napkin"], brand_id: 6, supplier_id: 3, name: "Blue Pearls", short_description: "", description: "Pack of 16 Napkins", permalink: "Blue Pearls", price_cents: 1590, discounted_price_cents: 1590, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Dinner Napkin"], brand_id: 6, supplier_id: 3, name: "Paris Dinner Napkin", short_description: "", description: "Pack of 16 Napkins", permalink: "Paris Dinner Napkin", price_cents: 1590, discounted_price_cents: 1590, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Dinner Napkin"], brand_id: 6, supplier_id: 3, name: "Blue Elegance", short_description: "", description: "Pack of 16 Napkins", permalink: "Blue Elegance", price_cents: 1590, discounted_price_cents: 1590, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Dinner Napkin"], brand_id: 6, supplier_id: 3, name: "Palais White Black", short_description: "", description: "Pack of 16 Napkins", permalink: "Palais White Black", price_cents: 1590, discounted_price_cents: 1590, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Textile Touch Napkins"], brand_id: 6, supplier_id: 3, name: "Black Velvet", short_description: "", description: "Pack of 12 Napkins", permalink: "Black Velvet", price_cents: 1850, discounted_price_cents: 1850, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Textile Touch Napkins"], brand_id: 6, supplier_id: 3, name: "Home Sweet Home", short_description: "", description: "Pack of 12 Napkins", permalink: "Home Sweet Home", price_cents: 1850, discounted_price_cents: 1850, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Textile Touch Napkins"], brand_id: 6, supplier_id: 3, name: "Velvet Cream Red", short_description: "", description: "Pack of 12 Napkins", permalink: "Velvet Cream Red", price_cents: 1850, discounted_price_cents: 1850, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Textile Touch Napkins"], brand_id: 6, supplier_id: 3, name: "Grey Amelie", short_description: "", description: "Pack of 12 Napkins", permalink: "Grey Amelie", price_cents: 1850, discounted_price_cents: 1850, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Textile Touch Napkins"], brand_id: 6, supplier_id: 3, name: "Classique Black", short_description: "", description: "Pack of 12 Napkins", permalink: "Classique Black", price_cents: 1850, discounted_price_cents: 1850, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""},
  {category_list: ["Dripless Taper Candles"], brand_id: 6, supplier_id: 3, name: "Gold Dripless Taper Candles", short_description: "", description: "6 Hour Long Burn Life. 24cm Tall", permalink: "Gold Dripless Taper Candles", price_cents: 900, discounted_price_cents: 900, meta_keywords: nil, meta_description: nil, stockable: true, home_featured: false, category_featured: false, available_at: nil, deleted_at: nil, description2: ""}
])
